version: '3.8'

services:
  db:
    container_name: ecommerce_db
    image: postgres:16
    restart: unless-stopped
    ports:
      - '3010:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    volumes:
      - db_data_ecommerce:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data_ecommerce: